<!DOCTYPE html>
    <html lang="en">
        <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.1.0/yeti/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
        <link rel="stylesheet" href="/app/assets/css/style.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
        <script defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
        <script defer src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
        <title>Title</title>
        </head>
        <div class="body_wrapper">
        <body>
        <header class="header">
            <div class="links">
        <a href="/home">Главная</a>
        <a href="/home/help">Вопросы и ответы</a>
        <a href="/home/about">Контакты</a>
        <a href="/home/portfolio">Тортики</a>
        <button class="callbutton">+7 999 000 90 09</button>
        </div>
        </header> 

        <main class="main">
            <?php include_once VIEW . $content_view ?>
        </main>
        <footer class="footer">
            <p>© 2018-2023 фабрика десертов Korovka</p>
        </footer>
        </body>
        </html>
    </body>
    </div>
</html>
