<div class="main_wrap_about">
<div class="map">
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2237.6247634416636!2d37.657962776652745!3d55.88652338168383!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46b5312c7c5a3357%3A0xc0ff6926ee207aac!2z0KHRi9GC0YvQuSDQu9C-0YHRjA!5e0!3m2!1sru!2sru!4v1687635471066!5m2!1sru!2sru" width="600" height="460" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
</div>
<div class="contacts"> 
<p>Медведково, улица Еловая, 1/173
<br>
бизнес-центр "Cытый лось холл"
<br>
<br>
Ежедневно <span class="colortext">10:00-20:00</span>
<br>
<br>
+7 999 000 90 09
<br>
+7 (1173) 00 90 09
<br>
<br>
<span class="colortext">hello@korovka.ru</span></p>
</div>
</div>